name: Simple Build

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch (adjust to your branch)

jobs:
  build:
    runs-on: self-hosted  # Run on your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Build successful"

