name: Trigger Jenkins Build

on:
  push:
    branches:
      - main  # Triggers only on push to main branch

jobs:
  trigger:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST http://localhost:8080/job/gem_test/build \
            --user admin:${{ secrets.JENKINS_API }}

