name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # Adjust to your branch if necessary

jobs:
  build:
    runs-on: self-hosted  # This is your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST http://localhost:8888/job/hello/build \
          --user new_admin:${{ secrets.JENKINS_API }}  # Using the secret correctly
        env:
          JENKINS_API: ${{ secrets.JENKINS_API }}
