name: Simple Build

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Build successful"
