name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # Adjust if your main branch is named differently

jobs:
  trigger:
    runs-on: self-hosted  # This uses your Docker-based self-hosted runner

    steps:
      - name: Trigger Jenkins Job from Localhost
        run: |
          curl -X POST http://localhost:8080/job/gem_test/build \
            --user admin:${{ secrets.JENKINS_API }}

